Generalize Frechet
stan-dev/math pull request #2029
Opened 2020-08-20 11:20 UTC by t4c1

## Summary

Generalizes Frechet distribution related functions to accept Eigen expressions.

## Tests

Tested using expression testing framework.

## Side Effects
None

## Release notes

Generalized Frechet distribution related functions to accept Eigen expressions.

## Checklist

- [ ] Math issue #1470

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

2020-09-04 00:23 UTC, bbbales2 requested changes
I guess just replace the logs and this is good.

2020-09-04 00:23 UTC, bbbales2 commented on stan/math/prim/prob/frechet_lccdf.hpp
> +      ops_partials.edge2_.partials_ = -log(y_val / sigma_val) * rep_deriv;
`log(x / y)` -> `log(x) - log(y)`

2020-09-04 00:23 UTC, bbbales2 commented on stan/math/prim/prob/frechet_cdf.hpp
> +    ops_partials.edge2_.partials_ = cdf * pow_n * log(y_val / sigma_val);
`log(x / y)` -> `log(x) - log(y)`

2020-09-04 09:37 UTC, t4c1 commented on stan/math/prim/prob/frechet_lcdf.hpp
> +    ops_partials.edge2_.partials_ = pow_n * log(y_val / sigma_val);
Performance-wise avoiding `log`s is better. However, from numerical stability point of view you are probably right.

2020-09-07 18:27 UTC, bbbales2 approved these changes

2020-09-07 18:27 UTC, merged