Runtime cl device selection
stan-dev/math pull request #2067
Opened 2020-09-08 11:57 UTC by t4c1

## Summary
Adds an option to select the OpenCL device to use at runtime. By default we stil use the device selected by macros.

Implementation of `kernel_cl` is also simplified.

## Tests
Added a test that checks everything works when switching devices. However that test truly checks anything only if it is running on a computer with multiple devices installed.

## Side Effects
Non-generated OpenCL kernels are compiled when used for the first time. This makes them consistent with how kernel generator works.

## Release notes
Added an option to select the OpenCL device to use at runtime.

## Checklist

- [ ] Math issue #(issue number)

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

2020-09-09 09:01 UTC, rok-cesnovar requested changes
Looks good. I have one minor question and a suggestion for a more informative comment.

2020-09-09 09:01 UTC, rok-cesnovar commented on test/unit/math/opencl/opencl_context_test.cpp
> +// this test only checks anything if there are multiple devices installed
```suggestion
// Checks that select_device() works for all devices found on the system. If there are multiple devices, this also tests that select_device() calls work after another device was already in use.
```

2020-09-09 09:04 UTC, t4c1 commented on stan/math/opencl/kernel_cl.hpp
> +    if (base_opts[it.first] > it.second) {
I think we had this discussion once. I think at the end you convinced me that > is the correct thing to use, although I don't remember the arguments.

2020-09-09 09:10 UTC, rok-cesnovar commented on stan/math/opencl/kernel_cl.hpp
> +    if (base_opts[it.first] > it.second) {
I think I now remember that the problem was if a device has a lower limit, say max group size is 10 and the compile_kernel calls with a higher limit that could be a problem. There is probably a better way of doing all this but that is a separate issue/PR.

2020-09-09 09:11 UTC, rok-cesnovar approved these changes

2020-10-02 12:58 UTC, t4c1 commented
The force push just removes all the debbuging code.

2020-10-08 07:48 UTC, rok-cesnovar approved these changes
LGTM.

Tested with the cmdstan branch and this seems to work great. Will open the cmdnstan PR  once this propagates upstream.

2020-10-08 07:49 UTC, merged