Opencl beta proportion lpdf
stan-dev/math pull request #2180
Opened 2020-11-03 09:11 UTC by t4c1

## Summary

Adds an OpenCL implementation of `beta_proportion_lpdf` function.

## Tests

Added tests.

## Side Effects

None.

## Release notes

Added an OpenCL implementation of `beta_proportion_lpdf` function.

## Checklist

- [ ] Math issue #2152 

- [ ] Copyright holder: Tadej Ciglarič

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

2020-11-09 18:10 UTC, bbbales2 commented
@t4c1 yo I've done the probability reviews up to here but I don't know how the OpenCL stuff works so you'll need to grab someone else from here on (which is why I haven't reviewed this).

2020-11-09 18:28 UTC, t4c1 commented
Yeah, that is fine. @rok-cesnovar will review these. There is no rush here.

2020-11-11 17:11 UTC, rok-cesnovar requested changes
A couple of questions, but otherwise looks good.

2020-11-12 14:50 UTC, t4c1 commented on stan/math/opencl/prim/beta_proportion_lpdf.hpp
> +  auto mukappa_expr = elt_multiply(mu_val, kappa_val);
In Eigen version matrices are converted to arrays, so * is the same as elt_multiply

2020-11-12 15:14 UTC, t4c1 commented on stan/math/opencl/prim/beta_proportion_lpdf.hpp
> +  auto mu_bounded_expr = 0 < mu_val && mu_val < 1;
In prim/prob this one actually uses `check_less` and `check_positive`, which do not allow boundary values.

2020-11-12 15:14 UTC, t4c1 commented on stan/math/opencl/prim/beta_proportion_lpdf.hpp
> +  auto log1m_y_expr = log1p(-y_val);
We don't OpenCL log1m, although I could add it.

2020-11-12 15:44 UTC, rok-cesnovar commented on stan/math/opencl/prim/beta_proportion_lpdf.hpp
> +  auto log1m_y_expr = log1p(-y_val);
Oh, not necessary just for this case.

2020-11-12 15:45 UTC, rok-cesnovar commented on stan/math/opencl/prim/beta_proportion_lpdf.hpp
> +  auto mu_bounded_expr = 0 < mu_val && mu_val < 1;
Ah yes, I mixed it up with y_val. We are cool.

2020-11-12 15:45 UTC, rok-cesnovar approved these changes

2020-11-12 15:45 UTC, merged