OpenCL: rev support for trigonometric functions
stan-dev/math pull request #2259
Opened 2020-12-15 12:57 UTC by rok-cesnovar

## Summary

This PR adds /rev OpenCL support for acos, acosh, asin, asinh, atan, atanh, cos, cosh, tan, tanh

## Tests

/

## Side Effects

/

## Release notes

OpenCL: added /rev support for acos, acosh, asin, asinh, atan, atanh, cos, cosh, tan, tanh

## Checklist

- [x] Math issue #1854 

- [x] Copyright holder: Rok Češnovar, Uni. of Ljubljana

2020-12-15 13:43 UTC, t4c1 requested changes

2020-12-15 13:43 UTC, t4c1 commented on stan/math/opencl/rev/tanh.hpp
> +    const matrix_cl<double>& cosh_A_val = cosh(A.val());
```suggestion
    auto cosh_A_val = cosh(A.val());
```
No need to eval it in a separate kernel. Kernel generator will deduplicate iit, so cosh will only be calculated once.

2020-12-15 13:43 UTC, t4c1 commented on test/unit/math/opencl/rev/acos_test.cpp
> +auto acos_functor = [](const auto& a) { return stan::math::acos(a).eval(); };
No need for eval.
```suggestion
auto acos_functor = [](const auto& a) { return stan::math::acos(a); };
```

2020-12-15 13:43 UTC, t4c1 commented on test/unit/math/opencl/rev/acos_test.cpp
> +auto acos_functor = [](const auto& a) { return stan::math::acos(a).eval(); };
Same for other tests.

2020-12-15 13:48 UTC, rok-cesnovar commented on test/unit/math/opencl/rev/acos_test.cpp
> +auto acos_functor = [](const auto& a) { return stan::math::acos(a).eval(); };
Done.

2020-12-15 13:55 UTC, t4c1 approved these changes

2020-12-16 12:39 UTC, t4c1 approved these changes

2020-12-16 21:34 UTC, merged