OpenCL: cleanup and rev support for add_diag, unary +-, mean, sub_col, sub_row, segment
stan-dev/math pull request #2272
Opened 2020-12-26 09:38 UTC by rok-cesnovar

## Summary

This PR does dome minor cleanup of /opencl and adds support for a few simple functions. In detail:
- removes copy_triangular, diagonal_multiply, identity and sub_block. The first was not used, other were replaced by k.g.
- added rev support for add_diag, unary operator+ (and plus()), unary operator- (and minus()), mean, sub_col, sub_row, segment

## Tests

All new functions are tested

## Side Effects

/

## Release notes

OpenCL: added rev support for add_diag, unary operator+ (and plus()), unary operator- (and minus()), mean, sub_col, sub_row and segment.

## Checklist

- [x] Math issue #1854 

- [x] Copyright holder: Rok Češnovar

2020-12-26 14:28 UTC, rok-cesnovar commented
Ready for review.

2020-12-28 09:31 UTC, t4c1 requested changes

2020-12-28 09:31 UTC, t4c1 commented on stan/math/opencl/tri_inverse.hpp
> +      = block_zero_based(inv_mat, 0, 0, inv_mat.rows(), inv_mat.rows());
```suggestion
      = inv_mat;
```

2020-12-28 09:31 UTC, t4c1 commented on stan/math/opencl/tri_inverse.hpp
> +      = block_zero_based(zero_mat, 0, 0, zero_mat.rows(), zero_mat.cols());
```suggestion
      = zero_mat;
```

2020-12-28 09:31 UTC, t4c1 commented on stan/math/opencl/tri_inverse.hpp
> +    block_zero_based(inv_mat, 0, 0, inv_mat.rows(), inv_mat.rows())
```suggestion
    inv_mat
```

2020-12-28 09:31 UTC, t4c1 commented on stan/math/opencl/tri_inverse.hpp
> +        = block_zero_based(zero_mat, 0, 0, zero_mat.rows(), zero_mat.cols());
```suggestion
        = zero_mat;
```

2020-12-28 09:31 UTC, t4c1 commented on stan/math/opencl/tri_inverse.hpp
> +  block_zero_based(inv_mat, 0, 0, inv_mat.rows(), inv_mat.rows())
```suggestion
  inv_mat
```

2020-12-28 13:22 UTC, t4c1 approved these changes

2020-12-28 17:01 UTC, merged