Added loglogistic cdf and rng
stan-dev/math pull request #2488
Opened 2021-05-07 12:01 UTC by gregorp90

## Summary

Implemented `loglogistic_cdf` with manual gradients and `loglogistic_rng` [#2320](https://github.com/stan-dev/math/issues/2320#issuecomment-781315580). The latter is based on sampling from Uniform(0, 1) and transforming the samples with the inverse cdf.

## Tests

Added a cdf to distribution tests and a rng test to unit tests.

## Release notes

Implementation of the loglogistic cumulative distribution function and random number generator.

## Checklist

- [ ] Math issue #2320

- [ ] Copyright holder: Gregor Pirš

2021-05-17 08:15 UTC, gregorp90 commented
@SteveBronder @t4c1 Hi, would anyone be up for reviewing this? Or recommend another reviewer? Thanks!

2021-05-17 09:02 UTC, t4c1 requested changes
cdf looks more or less good. I did not work much with rngs, so I would prefer if somebody else reviews that part. Maybe @bbbales2?

2021-05-17 14:40 UTC, bbbales2 commented
The rng implementation and tests look correct to me.

2021-05-17 15:46 UTC, gregorp90 commented on stan/math/prim/prob/loglogistic_cdf.hpp
> +        const auto& y_deriv = alpha_div_times_beta * inv(y_val) * prod_all_sq;
Thank you for the review! I will combine `y_deriv` with the next expression.

I have a question regarding your suggested change. I've been using the `inv` function here to guard against problems if both of the terms (`alpha_div_times_beta` and `y_val`) are integers. Or do we not need this, as these values are already converted to double or var somewhere along the line, maybe when we declare `y_ref`? On the other hand, we never come to this calculation if at least one of them is not var, so is that the reason why we can assume that one of these terms is not an integer? Just trying to fully understand the reasoning here so I can write better implementations next time.

2021-05-18 07:02 UTC, t4c1 commented on stan/math/prim/prob/loglogistic_cdf.hpp
> +        const auto& y_deriv = alpha_div_times_beta * inv(y_val) * prod_all_sq;
> On the other hand, we never come to this calculation if at least one of them is not var, so is that the reason why we can assume that one of these terms is not an integer?

That is fine, although it is non-trivial reasoning so maybe a comment in the code would be helpful. 

In other cases you can use `promote_scalar<double>(arg)` to convert one of the arguments to double and avoid integer division.

2021-05-18 09:48 UTC, gregorp90 commented on stan/math/prim/prob/loglogistic_cdf.hpp
> +        const auto& y_deriv = alpha_div_times_beta * inv(y_val) * prod_all_sq;
Great, thank you for the explanation! I will change the code according to your suggestions.

2021-05-18 13:35 UTC, t4c1 approved these changes

2021-05-18 18:23 UTC, merged