Have conditional_var_value_t return correct matrix type if scalar is var
stan-dev/math pull request #2491
Opened 2021-05-19 23:51 UTC by SteveBronder

## Summary

This just makes `conditional_var_value_t<var, Eigen::Matrix<var, -1, -1>>` returns back a `var_value<Eigen::Matrix<double, -1, -1>>`

## Tests

Test added for checking above behavior

```
./runTests.py ./test/unit/math/rev/meta/conditional_var_value_test.cpp
```

## Side Effects

Nope

## Release notes

Fixes case for `conditional_var_value_t`

## Checklist

- [x] Math issue #1805 

- [x] Copyright holder: (fill in copyright holder information)

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2021-05-20 07:21 UTC, t4c1 requested changes
Fix the doxygen according to the change.

2021-05-21 05:52 UTC, t4c1 commented on stan/math/rev/meta/conditional_var_value.hpp
>   * the type. This must be a prim type.
```suggestion
 * the type.
```
I meant this part. Sorry for the confusion.

2021-05-21 09:09 UTC, t4c1 approved these changes

2021-05-21 14:27 UTC, SteveBronder commented
@rok-cesnovar is it fine to merge this? It's a bug fix

2021-05-21 14:28 UTC, rok-cesnovar commented
Yeah, bugfixes are good.

2021-05-21 14:28 UTC, merged