Feature/matrix input to mvn [WIP]
stan-dev/math pull request #2540
Opened 2021-07-18 08:10 UTC by adamhaber

## Summary

Allow multivariate normal distribution to take in matrices for `y` and `mu` arguments (see #2532)

## Tests

Added a simple initial test for `lpdf` and `rng`, will add others (matching the tests for the non-matrix mvn?) if the current implementation makes sense.

## Side Effects

None.

## Release notes

Allow multivariate normal distribution to take in matrices for `y` and `mu` arguments.

## Checklist

- [ ] Math issue #2532 

- [ ] Copyright holder: Adam Haber

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [ ] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [ ] the code is written in idiomatic C++ and changes are documented in the doxygen

- [ ] the new changes are tested

2021-07-18 08:24 UTC, andrjohns commented
For the `_lpdf` functions, would it be easier to just call `to_vector` on the inputs? Then the existing vector inputs are unchanged but the matrix inputs are mapped to vectors and the rest of the function proceeds as normal? That might allow for more to be vectorised?

2021-07-18 09:11 UTC, adamhaber commented
Do you mean transforming `y` and `mu` from `[N,M]` matrices to `N*M` vectors?

2021-07-18 10:12 UTC, andrjohns commented
I was initially, but now I realise that doesn't make much sense in this context, where the y/mu dimensions need to match sigma's. What i was thinking would only really make sense for passing matrices to the univariate distributions

2021-07-20 17:35 UTC, SteveBronder commented
Thanks Adam! I made an example of what I think would be nice here you can check out in the diff below

What we want to do is utilize the matrix inputs for more efficient code than the standard mvn. So in the below instead of having to call `trace_inv_quad_form_ldlt` for each row we can just call it once. Would you be able to take something like I have in the below and apply it to the other multivariate normal distributions? Ideally this would be rad to have for all the multivariate distributions but we can do these piece by piece

https://github.com/stan-dev/math/compare/review/mvn-matrix?expand=1

2022-04-29 04:09 UTC, syclik commented
Closing this for now since it's still in draft. @adamhaber, please reopen if it's active.

2022-04-29 04:10 UTC, syclik commented
Sorry... I didn't realize it wasn't a draft. Reopening.

2022-04-29 04:16 UTC, syclik requested changes
Thanks for the PR!

Please add a unit test for different sizes. I believe it should throw an `std::illegal_argument` exception so that sampling stops.

2022-04-29 04:16 UTC, syclik commented on stan/math/prim/prob/multi_normal_lpdf.hpp
> +  lp_type lp(0.0);
Could you take away the `using lp_type...` statement on 111 and declare `lp` as that type? It's easier to read when that's together.

2022-04-29 04:16 UTC, syclik commented on stan/math/prim/prob/multi_normal_lpdf.hpp
> +    auto current_y = y.row(n);
Is this code safe? What happens if `y` and `mu` have different lengths? Won't this just read off the end?

I'd like to see this fixed before it gets into the code base. Perhaps use a `check_matching_sizes` or something similar?

2022-04-29 04:16 UTC, syclik commented on test/unit/math/prim/prob/multi_normal_test.cpp
> +
Please add a test where `y` and `mu` have different number of rows. This will trigger a failure and we should know what that is through a unit test.

2022-04-29 04:17 UTC, syclik commented
Sorry, it is a draft! I'm closing it until it's ready to be reopened.

2022-04-29 04:17 UTC, closed without merging