rewrite log_determinant_spd rev using arena
stan-dev/math pull request #2719
Opened 2022-04-28 10:04 UTC by spinkney

## Summary

Updates the `log_determinant_spd` function using the arena syntax.

## Tests

No new tests. 

## Side Effects

None

## Release notes

## Checklist

- [x] Math issue #2718

- [x] Copyright holder: Sean Pinkney

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2022-04-28 17:08 UTC, SteveBronder requested changes
Very nice cleanup! Few small things. We should use `solveInPlace()` so we don't need to allocate extra memory and we can re-use `m_d` in a few more places

2022-04-28 17:08 UTC, SteveBronder commented on stan/math/rev/fun/log_determinant_spd.hpp
> +template <typename T, require_rev_matrix_t<T>* = nullptr>
(optional) I prefer slightly more informative names, like `Mat` or even just `M` for matrix

2022-04-28 17:08 UTC, SteveBronder commented on stan/math/rev/fun/log_determinant_spd.hpp
> + * @tparam T Type is an Eigen Matrix
```suggestion
 * @tparam T Type is an Eigen Matrix or `var_value` with inner Eigen matrix type
```

2022-04-28 19:21 UTC, spinkney commented
@SteveBronder thanks for the review! I've addressed the comments and it's ready for another.

2022-05-03 21:02 UTC, SteveBronder requested changes
Looks good but one little thing. We want to make sure that Eigen actually evaluates that ldlt call before we do any checking to it. (tbh I'm just not sure if `auto` actually evaluates the ldlt call here and would rather call the eval to make sure)

2022-05-03 21:02 UTC, SteveBronder commented on stan/math/rev/fun/log_determinant_spd.hpp
> +  auto M_ldlt = M_d.ldlt();
```suggestion
  auto M_ldlt = M_d.ldlt().eval();
```

2022-05-03 21:06 UTC, spinkney commented on stan/math/rev/fun/log_determinant_spd.hpp
> +  auto M_ldlt = M_d.ldlt();
cool, this is still magic to me.

2022-05-03 22:24 UTC, spinkney commented
> Looks good but one little thing. We want to make sure that Eigen actually evaluates that ldlt call before we do any checking to it. (tbh I'm just not sure if `auto` actually evaluates the ldlt call here and would rather call the eval to make sure)

It says ldlt has no member name eval()
https://github.com/stan-dev/math/runs/6280503158?check_suite_focus=true#step:7:1684

2022-05-03 22:35 UTC, SteveBronder commented
Oh sorry! Then it's fine to remove it

2022-05-03 23:41 UTC, spinkney commented
@SteveBronder done!

2022-05-04 18:12 UTC, SteveBronder approved these changes
As long as tests pass this is good!

2022-05-05 08:45 UTC, merged