Add to_int function and tests
stan-dev/math pull request #2771
Opened 2022-06-28 10:48 UTC by andrjohns

## Summary

This PR adds a function for casting `double` and `std::vector<double>` inputs to `int` types. This is intended to only be exposed for use with `data real` and `array[] data real` types in Stan

## Tests

Prim tests added for correctness of return as well as throwing if the input is too large to be represented as an `int` without overflowing

## Side Effects

N/A

## Release notes

Added function for casting `double` and `std::vector<double>` types to `int` and `std::vector<int>` types

## Checklist

- [x] Math issue #2770 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2022-06-28 21:15 UTC, bob-carpenter requested changes
this needs a bit more doc and a bit more testing, but otherwise looks good

2022-06-28 21:15 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> + * @return iIteger value of argument
typo here

2022-06-28 21:15 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> + */
need to document when it throws

2022-06-28 21:15 UTC, bob-carpenter commented on test/unit/math/prim/fun/to_int_test.cpp
> +}
Need to test NaN behavior.

It'd be nice to test +/- inf behavior.

2022-06-28 21:15 UTC, bob-carpenter commented on test/unit/math/prim/fun/to_int_test.cpp
> +
test empty vectors and size 1 vectors (this should all work given the way it's defined, but the boundary tests should still be in place).

I'm not sure we really need to test bigger containers or other types of containers like `vector<MatrixXd>`, etc.

2022-06-28 21:15 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> +inline int to_int(T x) {
[optional]
probably not worth specializing, but this is an inefficient implementation for `int` inputs because of the unnecessary tests

2022-06-28 21:15 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> + * Returns the input scalar as an integer type
This needs to be much more specific in terms of how it returns.  You can say it truncates using `static_cast<int>` to be precise, but something needs to say how it converts.

2022-06-30 07:35 UTC, andrjohns commented
The `Rtools40 mix/fun` failures are just the actions hitting the 6hr time limit and being automatically terminated, rather than actual test failures. Given that `to_int()` isn't touching anything in `rev`/`fwd`, and the Jenkins `mix/fun` tests passed, I'd say that this was safe to approve (and merge after the freeze)

2022-07-05 16:27 UTC, bob-carpenter requested changes
really just a minor doc change and message change (and optionally cutting out the nan and finite tests)

2022-07-05 16:27 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> + * @return Integer value of argument
needs to doc @throw when out of bounds or NaN

2022-07-05 16:27 UTC, bob-carpenter commented on stan/math/prim/fun/to_int.hpp
> +  if (x < std::numeric_limits<int>::min()
the check-finite test is redundant and the check-not-nan is also redundant if you rewrite as:

```cpp
if (!(x >= std::numeric_limits<int>::min() && x <= std::numeric_limits<int>::max())) { ... }
```
And the message should be that the value is not in range to be converted to integer (it's either too large if it's above max or too small if it's below min and it doesn't fit if it's NaN).

2022-07-07 19:06 UTC, bob-carpenter approved these changes

2022-07-07 19:06 UTC, merged