Fix/docs2
stan-dev/math pull request #2805
Opened 2022-08-16 20:08 UTC by SteveBronder

## Summary

I'm breaking up #2687 into several smaller pieces as the other PR was error'ing out in some odd places and that large of a PR is hard to debug. I think I'm going to do it like 

- [ ] Fix up documentation website
- [ ] Fix up docs for meta functions like `value_type_t` etc.
- [ ] Several small Prs to remove errors from `argument 'x' from the argument list of <FUNCTION> has multiple @param documentation sections`

## Tests

Only doc changes so no new tests

## Side Effects

Nope

## Release notes

Update math library documentation

## Checklist

- [ ] Math issue #(issue number)

- [x] Copyright holder: Steve Bronder

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Code-Quality) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2022-08-17 16:10 UTC, bob-carpenter commented
Thanks so much for finishing the revised PR. 

I'm not going to review, because I don't understand the new math lib's C++ well enough.  Ideally, someone would have the time to follow along and see if the instructions work.    Barring that, I'd suggest someone who understands the C++ already.  Perhaps @rok-cesnovar or @wds15 or @andrjohns?

2022-08-17 17:38 UTC, SteveBronder commented
That's reasonable. If any of the three of yinz also have contributions that you think would help out the docs absolutely feel free to add to the branch!

2022-08-18 09:49 UTC, rok-cesnovar commented
Will review it this weekend! Thanks Steve!

2022-08-28 09:48 UTC, rok-cesnovar requested changes
Looks great to me. Some grammar/typo comments, but all are rather small. No objections in terms of content/organization.

2022-09-13 19:56 UTC, WardBrian commented
Are there any objections to committing @rok-cesnovar's grammar suggestions and then merging this? I've had a few people recently ask me about getting started docs here

2022-09-14 20:12 UTC, bob-carpenter commented
> Are there any objections to committing @rok-cesnovar's grammar suggestions and then merging this?

Yes, I think it's better than what we have now and I don't think @SteveBronder has much time to revise.  

I gave Steve a pile of feedback on the text---I just didn't want to be a final reviewer because I don't understand the C++ well enough and don't have time to verify it all.

2022-09-15 01:28 UTC, SteveBronder commented
Hey srry! Been busy ill look at this tmrw and make the changes

2022-09-15 13:19 UTC, WardBrian commented
No worries Steve! I wasn't asking to try to rush you, but more ask if you wanted someone else (e.g. me) to go through Rok's suggestions and then merge this

2022-09-22 13:39 UTC, WardBrian commented
I just went through all of @rok-cesnovar's grammar and spelling line edits, so assuming he is okay with the content of this I believe we should merge after CI

2022-09-22 15:09 UTC, rok-cesnovar submitted a review, later dismissed

2022-09-23 14:35 UTC, rok-cesnovar approved these changes

2022-09-27 17:35 UTC, merged