Add rev functor to compute hessian-times-vector by finite differences
stan-dev/math pull request #2914
Opened 2023-06-16 14:36 UTC by WardBrian

## Summary

This adds a function analogous to `finite_diff_hessian_auto` for computing Hessian-vector products of functions which only support `rev` mode types. This can be done with only two calls to `gradient`, compared to the `2N` calls needed for the naive approach of using `finite_diff_hessian_auto` and then multiplying.

The approach is described by @justindomke here: https://justindomke.wordpress.com/2009/01/17/hessian-vector-products/

In short, 

If $g(x) =  \frac{\partial f}{\partial x} f(x)$, then $g(x+\Delta x) \approx g(x) + H(x)\Delta x$
So
$H(x)v \approx \frac{g(x + rv) - g(x - rv)}{2r}$

See also: discussion in roualdes/bridgestan#126
## Tests

I have duplicated the existing test used for autodiff Hessian-vector products. There is only one, so more might be nice.

## Side Effects

None

## Release notes

New function in `stan::math::internal`, `finite_diff_hessian_vector_product_auto`

## Checklist

- [x] Math issue: closes #2913 

- [x] Copyright holder: Simons Foundation

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2023-06-16 16:16 UTC, aseyboldt commented
I don't think it is valid to choose a different epsilon for each dimension, wouldn't that just change the vector we multiply the hessian with?

2023-06-16 16:26 UTC, WardBrian commented
> I don't think it is valid to choose a different epsilon for each dimension, wouldn't that just change the vector we multiply the hessian with?

I think you're right - this just so happened to have worked because the `finite_diff_stepsize` function uses 
`stepsize(u) = cbrt(epsilon) * max(1, abs(u))`, and because v is normalized `max(1,u)` is one always, so the cube root of epsilon is used. 

Do you think there is a better way of automatically deciding an epsilon, or should I just skip the call to `finite_diff_stepsize` and use cbrt(epsilon)?

2023-06-16 16:33 UTC, aseyboldt commented
> Do you think there is a better way of automatically deciding an epsilon, or should I just skip the call to finite_diff_stepsize and use cbrt(epsilon)?

I don't know of any better way, but that doesn't mean there isn't one... :-)

2023-06-27 08:05 UTC, andrjohns requested changes

2023-06-27 08:05 UTC, andrjohns commented on stan/math/rev/functor/finite_diff_hessian_times_vector_auto.hpp
> +  double epsilon = std::sqrt(EPSILON) * (1 + x.norm()) / v_norm;
```suggestion
  double epsilon = std::sqrt(EPSILON) * (1 + x.norm()) / v.norm();
```

2023-06-27 08:05 UTC, andrjohns commented on stan/math/rev/functor/finite_diff_hessian_times_vector_auto.hpp
> +  fx = f(x);
This doesn't seem to be used anywhere, safe to remove?

2023-06-27 13:31 UTC, andrjohns submitted a review, later dismissed
LGTM!

2023-06-28 14:19 UTC, WardBrian commented
@andrjohns mind re-approving? The auto formatting commit dismissed your last review

2023-06-29 06:52 UTC, andrjohns approved these changes

2023-06-29 06:53 UTC, merged