Fix: eigenvalues returns column vector
stan-dev/math pull request #2915
Opened 2023-06-16 19:31 UTC by WardBrian

## Summary

Eigen's eigensolvers return column vectors, but the current return type is set to a row vector. This causes issues such as https://github.com/stan-dev/stan/issues/3199

## Tests

## Side Effects

## Release notes

Fixed an issue with the return type of `eigenvalues` being incorrect

## Checklist

- [x] Math issue: Closes stan-dev/stan#3199

- [x] Copyright holder: Simons Foundation

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2023-06-24 11:10 UTC, syclik requested changes
"Request changes" turned on so I have a little bit of time to look at how the return types could have gotten through.

2023-06-24 11:10 UTC, syclik commented on stan/math/prim/fun/eigenvalues.hpp
> +inline Eigen::Matrix<complex_return_t<value_type_t<EigMat>>, -1, 1> eigenvalues(
The change looks good, but before merging, I'd like to look at the types and tests for the function to see how this wasn't trapped prior to this merge.

2023-06-26 20:43 UTC, WardBrian commented
@syclik - anything I can do to help?

2023-06-29 19:20 UTC, syclik commented
Thanks! I'm approving and let's get this merged. 

I don't think this PR needs to wait any longer. I still want to see how this is happening. 

After this issue, I'm even more adamant on not using `auto` for return types except where there's a really good reason for it. Types really provide a lot of information for the developer.

2023-06-29 19:21 UTC, syclik approved these changes
LGTM! Thanks!!

2023-06-29 19:21 UTC, merged