Add binomial_logit_glm distribution
stan-dev/math pull request #2946
Opened 2023-09-20 06:28 UTC by andrjohns

## Summary

This PR adds the `binomial_logit_glm_lpmf` distribution, the binomial equivalent of the `bernoulli_logit_glm_lpmf`. Much of the log-probability and derivative construction is the same between the two, so this implementation closely follows the existing `bernoulli_logit_glm_lpmf` implementation.

## Tests

All valid scalar/container combinations tested via:

- `prim` tests for equality with `binomial_logit(alpha + x*beta)` and throwing behaviour
- `mix` tests 

## Side Effects

N/A

## Release notes

`binomial_logit_glm_lpmf` distribution added

## Checklist

- [x] Math issue #1964 

- [x] Copyright holder: Andrew Johnson

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2023-10-04 14:09 UTC, SteveBronder requested changes
I think overall lgtm, one little doc change. Also shouldn't this have tests in the distribution tests setup?

2023-10-05 12:04 UTC, andrjohns commented on stan/math/prim/prob/binomial_logit_glm_lpmf.hpp
> +/** \ingroup multivar_dists
Good catch!

2023-10-05 12:04 UTC, andrjohns commented on stan/math/prim/prob/binomial_logit_glm_lpmf.hpp
> +  const auto& N_val = as_value_column_array_or_scalar(N_ref);
Makes sense, I updated these and some other `ref`-handling for robustness as well

2023-10-05 12:05 UTC, andrjohns commented
> Also shouldn't this have tests in the distribution tests setup?

As far as I can tell that's not possible, since I believe the distribution tests only support all scalar inputs. I also couldn't find any distribution tests for the existing GLM functions in there either

2023-10-05 17:46 UTC, SteveBronder approved these changes
lgtm!

2023-10-06 04:12 UTC, merged