Experimental/laplace
stan-dev/math pull request #3097
Opened 2024-07-22 16:43 UTC by SteveBronder

## Summary

Draft pull request for laplace approximation in Stan

## Tests

## Side Effects

## Release notes

## Checklist

- [x] Copyright holder: Simon's Foundation

    The copyright holder is typically you or your assignee, such as a university or company. By submitting this pull request, the copyright holder is agreeing to the license the submitted work under the following licenses:
      - Code: BSD 3-clause (https://opensource.org/licenses/BSD-3-Clause)
      - Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

- [x] the basic tests are passing

    - unit tests pass (to run, use: `./runTests.py test/unit`)
    - header checks pass, (`make test-headers`)
    - dependencies checks pass, (`make test-math-dependencies`)
    - docs build, (`make doxygen`)
    - code passes the built in [C++ standards](https://github.com/stan-dev/stan/wiki/Coding-Style-and-Idioms) checks (`make cpplint`)

- [x] the code is written in idiomatic C++ and changes are documented in the doxygen

- [x] the new changes are tested

2024-07-22 22:02 UTC, SteveBronder commented
I'm closing this for now. Just needed the pr for looking at the diff

2024-12-14 20:04 UTC, SteveBronder commented on stan/math/mix/functor/laplace_likelihood.hpp
> +  for (Eigen::Index i = 0; i < hessian_block_size; ++i) {
Note for myself. I think for a large enough Hessian block size we could run this loop using a tbb parallel for loop

2025-04-01 15:32 UTC, SteveBronder commented on stan/math/mix/prob/laplace_poisson_log_exposure_rng.hpp
> + * @param args
@charlesm93 these need doc'd

2025-04-22 15:59 UTC, WardBrian commented on stan/math/mix/prob/laplace_marginal_neg_binomial_2_log_lpmf.hpp
> +      const Eigen::Matrix<T_theta, Eigen::Dynamic, 1>& theta, const T_eta& eta,
Ok, I've spent some time trying to get this to compile in my stanc3 branch and I think the issue is this is too restrictive/needs to be a template, in order to be able to pass `data` matrices here. I'm getting 

```
stan/lib/stan_math/stan/math/mix/functor/laplace_likelihood.hpp:32: error: no match for call to ‘(stan::math::neg_binomial_2_log_likelihood) (const Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >&, const Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >&, const std::vector<int>&, const std::vector<int>&, std::basic_ostream<char>*&)’
   32 |   return std::forward<F>(f)(std::forward<Theta>(theta),
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   33 |                             std::forward<Args>(args)...);
      | 
stan/lib/stan_math/stan/math/mix/prob/laplace_marginal_neg_binomial_2_log_lpmf.hpp:28: note: candidate: ‘template<class T_theta, class T_eta> stan::return_type_t<T1, T2> stan::math::neg_binomial_2_log_likelihood::operator()(const Eigen::Matrix<Type, -1, 1>&, const T_eta&, const std::vector<int>&, const std::vector<int>&, std::ostream*) const’
   28 |   inline return_type_t<T_theta, T_eta> operator()(
      | 
stan/lib/stan_math/stan/math/mix/prob/laplace_marginal_neg_binomial_2_log_lpmf.hpp:28: note:   template argument deduction/substitution failed:
stan/lib/stan_math/stan/math/mix/functor/laplace_likelihood.hpp:32: note:   ‘const Eigen::Map<Eigen::Matrix<double, -1, 1>, 0, Eigen::Stride<0, 0> >’ is not derived from ‘const Eigen::Matrix<Type, -1, 1>’
   32 |   return std::forward<F>(f)(std::forward<Theta>(theta),
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   33 |                             std::forward<Args>(args)...);
      | 
```

I think the same might be true for `y` in `bernoulli_logit_likelihood` above.

cc @SteveBronder

2025-04-24 16:43 UTC, WardBrian commented on stan/math/rev/core/nested_rev_autodiff.hpp
This is causing compilation problems on older clangs (like what we use in CI) -- https://jenkins.flatironinstitute.org/blue/organizations/jenkins/Stan%2FStanc3/detail/PR-1513/18/pipeline/

It also looks like these changes are unused?

2025-04-29 16:54 UTC, SteveBronder commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +};
@charlesm93 can you check these defaults are correct?

2025-05-01 14:39 UTC, WardBrian commented
`laplace_marginal_neg_binomial_log_summary_lpmf_test` took ~5 hours to run (not counting compilation) on the latest push. `laplace_marginal_poisson_log_lpmf_test` took even longer. I don't think we can (unconditionally, at least) run those kinds of test in our CI pipeline

2025-05-01 17:24 UTC, SteveBronder commented
Before I cut out a lot of tests I want to try building a separate jenkins node that just compiles these. At O3 these tests run decently quickly

2025-05-08 20:13 UTC, SteveBronder commented on stan/math/mix/functor/laplace_base_rng.hpp
> +                                        RNG& rng, std::ostream* msgs) {
@charlesm93 check the math on this function to make sure we predict on the training data correctly.

2025-05-28 13:41 UTC, WardBrian commented
Changing the namespace of is_tuple will also require changes up in Stan. Not sure it's worth doing as part of this

2025-05-28 14:32 UTC, SteveBronder commented
Oh good call I'll put that back

2025-05-28 20:40 UTC, WardBrian requested changes
Bunch of comments from in-person review. Should be good to go once addressed

2025-05-28 20:40 UTC, WardBrian commented on Jenkinsfile
> +                        sh "echo CXXFLAGS += -fsanitize=address -march=native -mtune=native >> make/local"
I would move -fsanitize=address to the if below that only runs on dev/master

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/hessian_block_diag.hpp
Test for this function please!

2025-05-28 20:40 UTC, WardBrian commented on test/unit/math/prim/functor/iter_tuple_n_test.cpp
Empty file -- missing check in?

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/iter_tuple_n.hpp
> +inline auto iter_tuple_n(F&& f, Types&&... args) {
I assume `n` is for nested, in which case I would prefer just calling it nested

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/iter_tuple_n.hpp
> +inline auto iter_tuple_n(F&& f, Types&&... args) {
Also, return type should be `void`

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/iter_tuple_n.hpp
> +  } else if constexpr (is_vec_container) {
Verify that this check is only triggering for vectors of tuples (e.g, not vectors of matrices).

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/apply.hpp
> +
Delete

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/apply.hpp
> +#include <iostream>
Delete

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/apply.hpp
> +
Delete? If not, comment

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/meta/contains_tuple.hpp
> +template <template <typename...> class Filter, typename T>
Move these to filter_map.hpp

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/filter_map.hpp
> + * element of an `std::vector` your type trait must do that itself.
If we always need it to go into the vector, we can make that the default and this would be clearer.

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/filter_map.hpp
> +            return stan::math::tuple_concat(filter_map<Filter, false, true>(
I think it's worth calling out the tuple_concat here to explain why the non-IsVector branches below always return tuples

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/filter_map.hpp
> + * element of an `std::vector` your type trait must do that itself.
I think it would really help to call out an example use case of this function in this comment

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +            covar_args_copy);
This style of call to filter map is repeated a couple places, I think it makes sense to pull it into a helper function

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/map_if.hpp
> +
Delete

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/partially_forward_as_tuple.hpp
> +}  // namespace internal
Delete?

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/functor/partially_forward_as_tuple.hpp
> +inline constexpr auto partially_forward_as_tuple(Types&&... args) {
Optional: Another name would be nice, maybe `materialize` or `copy` rather than forward as the verb.

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/meta/is_all_arithmetic.hpp
> +namespace stan {
Rather than one specific is_all_*, want to make an stan::is_arithmetic? This would be useful in the compiler, where we currently generate `std::is_arithmetic<std::decay_t<T>>`

2025-05-28 20:40 UTC, WardBrian commented on stan/math/rev/core/accumulate_adjoints.hpp
> +
Delete?

2025-05-28 20:40 UTC, WardBrian commented on stan/math/rev/core/count_vars.hpp
> +inline size_t count_vars_impl(size_t count, std::basic_ostream<char>*&);
Delete -- maybe revert whole file?

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_likelihood.hpp
> +enum class COPY_TYPE { SHALLOW = 0, DEEP = 1 };
Docstring

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_likelihood.hpp
> +  fvar<var> f_fvar = stan::math::apply(
Hard to read

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +  int64_t max_num_steps{100};
aside: users won't be able to exceed 32 bit ints for this anyway

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/fun/Eigen.hpp
> +#include <unsupported/Eigen/MatrixFunctions>
IMO we should include these unsupported headers only in the files that need them, like we do for e.g. FFT

2025-05-28 20:40 UTC, WardBrian commented on stan/math/prim/fun/value_of_rec.hpp
> +  if constexpr (is_plain_type<T>::value || is_holder_v<T>) {
Also check if expression, evaluate or wrap in holder. Same for value_of()

2025-05-28 20:40 UTC, WardBrian commented on stan/math/rev/fun/adjoint_of.hpp
Check that these changes are really necessary

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +                1,
This should be `static_assert(0` (or `false`) -- check other usages as well.

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +              std::move(Eigen::MatrixXd(L)),
No need to move a temporary

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +            std::move(Eigen::MatrixXd(L)),
Same

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/functor/laplace_marginal_density.hpp
> +inline void print_adjoint(Output&& output) {
Move to test file

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/prob/laplace_marginal.hpp
> +  // TEST: provisional signature to agree with parser.
Delete

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/prob/laplace_marginal_neg_binomial_2_log_lpmf.hpp
> +struct neg_binomial_2_log_likelihood_summary {
If we want to keep this, @charlesm93 needs to add it to his doc PR and I need to add it to the compiler (both should be easy)

2025-05-28 20:40 UTC, WardBrian commented on stan/math/mix/prob/laplace_marginal_poisson_log_exposure_lpmf.hpp
Should we have the filename and function match? `exposure` or `2`? @charlesm93

2025-05-30 15:41 UTC, SteveBronder commented on stan/math/mix/prob/laplace_marginal_poisson_log_exposure_lpmf.hpp
I made both of these `2`

2025-05-31 21:23 UTC, WardBrian commented
Without ASAN, the laplace tests only took 16 minutes? Does that sound right? @SteveBronder

2025-05-31 22:07 UTC, SteveBronder commented
Yeah locally they take about 20 minutes

2025-05-31 22:08 UTC, SteveBronder commented
Let me give this one hard look on Sunday then Monday we merge and Tuesday we release!

2025-05-31 22:11 UTC, WardBrian commented
16 minutes -> 4 hours using ASAN is one of the worst slowdowns I’ve ever seen for a sanitizer run. Wow

2025-05-31 22:12 UTC, WardBrian approved these changes

2025-06-02 20:52 UTC, merged

2025-06-02 20:52 UTC, SteveBronder commented
@WardBrian merged! Tuesday lets merge the stanc3 pr then we are good to release!